<template>
  <admin-product-layout title="상품 상세">
    <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
    <template v-if="product">
      <section class="summary"><div class="images"><img v-for="image in product.images" :key="image.productImageNo" :src="imageUrl(image.imageUrl)" :alt="product.productNameKo"></div><div><p class="code">{{ product.productCode }} · No. {{ product.productNo }}</p><h2>{{ product.productNameKo }}</h2><p>{{ product.productNameEn }}</p><strong>{{ currency(product.discountPrice || product.salePrice) }}</strong><span>{{ statusLabel(product.productStatus) }}</span></div></section>
      <section class="details"><h2>상품 정보</h2><dl><template v-for="item in detailItems"><dt :key="`${item.label}-dt`">{{ item.label }}</dt><dd :key="`${item.label}-dd`">{{ item.value }}</dd></template></dl></section>
      <section class="description"><h2>상품 설명</h2><p>{{ product.shortDescription || '-' }}</p><div>{{ product.detailDescription || '-' }}</div></section>
      <router-link class="back" :to="{ name: 'adminProductList' }">목록으로</router-link>
    </template>
  </admin-product-layout>
</template>
<script>
import AdminProductLayout from '@/components/admin/AdminProductLayout.vue'; import { getAdminProduct } from '@/api/admin.js'; import envs from '@/envs'
export default { name: 'AdminProductDetailView', components: { AdminProductLayout }, data: () => ({ product: null, errorMessage: '' }), computed: { detailItems () { const p = this.product; return [{ label: '판매자', value: p.sellerName }, { label: '브랜드', value: p.brandName || '-' }, { label: '카테고리', value: p.categoryName }, { label: '원가', value: this.currency(p.costPrice) }, { label: '판매가', value: this.currency(p.salePrice) }, { label: '할인가', value: p.discountPrice == null ? '-' : this.currency(p.discountPrice) }, { label: '재고 / 안전재고', value: `${p.stockQuantity} / ${p.safetyStockQuantity}` }, { label: '사용 / 전시', value: `${p.useYn} / ${p.displayYn}` }, { label: '전시기간', value: `${p.displayStartDate || '-'} ~ ${p.displayEndDate || '-'}` }, { label: '제조사 / 원산지', value: `${p.manufacturer || '-'} / ${p.originCountry || '-'}` }, { label: '배송', value: `${p.shippingType} / ${this.currency(p.shippingFee)}` }] } }, created () { getAdminProduct(this.$route.params.productNo).then(({ data }) => { this.product = data }).catch(() => { this.errorMessage = '상품 정보를 불러오지 못했습니다.' }) }, methods: { currency (v) { return `${Number(v || 0).toLocaleString('ko-KR')}원` }, imageUrl (path) { return `${envs.apiBaseUrl.replace(/\/api$/, '')}${path}` }, statusLabel (s) { return { READY: '판매대기', ON_SALE: '판매중', SOLD_OUT: '품절', SALE_ENDED: '판매종료', SALE_COMPLETED: '판매완료' }[s] || s } } }
</script>
<style lang="scss" scoped>
section { margin-top: 24px; padding: 28px; border: 1px solid #dce5e3; background: #fff; } .summary { margin-top: 36px; display: grid; grid-template-columns: 320px 1fr; gap: 32px; } .images { display: flex; overflow-x: auto; } .images img { width: 300px; height: 300px; flex: 0 0 auto; object-fit: cover; } .code { color: #78908c; font-size: 11px; } .summary h2 { font-size: 28px; } .summary strong { margin: 28px 0 14px; display: block; font-size: 24px; } .summary span { padding: 7px 10px; background: #dceae7; font-size: 11px; } dl { display: grid; grid-template-columns: 160px 1fr; } dt,dd { margin: 0; padding: 13px; border-bottom: 1px solid #e5ebe9; font-size: 12px; } dt { color: #748783; } .description div { white-space: pre-wrap; line-height: 1.8; } .back { margin-top: 20px; padding: 12px 20px; display: inline-block; background: #183c43; color: #fff; text-decoration: none; } .error { color: #b14949; } @media(max-width:800px){.summary{grid-template-columns:1fr}.images img{width:240px;height:240px}}
</style>
